encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}
token:
  secret-key: ${TOKEN_SECRET_KEY}
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    #      password: yourPassword
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: ${MONGODB_AUTH_DB}
      database: ${MONGODB_DB}
