spring:
  profiles:
    default: local
  config:
    import: classpath:application-secrets.yml
  application:
    name: authorization
encrypt:
  iv:
    length: 12
    t-len: 128
#  secret-key: yourSecretBase64Key
token:
  expiration-ms: 60000
  employee-sub: com.jobby.employee
  default-iss: com.jobby.authorization
  #  secret-key: yourSecretBase64Key-256bits
  refresh-expiration-ms: 120000
