spring:
  config:
    import: classpath:application-secrets.yml
  application:
    name: authorization
  data:
    redis:
      host: localhost
      port: 6379
#      password: yourPassword
    mongodb:
      host: localhost
      port: 27017
#      username: yourUsername
#      password: yourPassword
      authentication-database: admin
      database: jobby
server:
  port: 8080
encrypt:
  iv:
    length: 12
    t-len: 128
#  secret-key: yourSecretBase64Key
token:
  expiration-ms: 60000
  employee-sub: com.jobby.employee
  default-iss: com.jobby.authorization
  #  secret-key: yourSecretBase64Key-256bits
  refresh-expiration-ms: 120000