services:

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8090:8080"
    environment:
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: container
    networks:
      - internal-net

  authorization:
    build:
      context: .
      dockerfile: authorization/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
      TOKEN_SECRET_KEY$: ${TOKEN_SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_AUTH_DB: ${MONGODB_AUTH_DB}
      MONGODB_DB: ${MONGODB_DB}
      SPRING_PROFILES_ACTIVE: container
    networks:
      - internal-net
      - mongodb-net
      - redis-net

  employee:
    build:
      context: .
      dockerfile: employee/Dockerfile
    ports:
      - "8082:8080"
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      SPRING_PROFILES_ACTIVE: container
    networks:
      - internal-net
      - mariadb-net

networks:
  internal-net:
  mariadb-net:
    external: true
    name: jobby-mariadb-net
  mongodb-net:
    external: true
    name: jobby-mongodb-net
  redis-net:
    external: true
    name: jobby-redis-net