services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    command: --log-bin=mysql-bin --binlog-format=ROW --server-id=1
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      SPRING_PROFILES_ACTIVE: container
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - mariadb-net
      - messaging-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - redis-net

volumes:
  mariadb-data:
  mongodb-data:
networks:
  mariadb-net:
    name: jobby-mariadb-net
    driver: bridge
  mongodb-net:
    name: jobby-mongodb-net
  redis-net:
    name: jobby-redis-net
  messaging-net:
    name: jobby-messaging-net
    external: true