server:
  port: 8090
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: employee-rest-api
              uri: http://localhost:8081
              predicates:
                - Path=/api/employee/**
              filters:
                - StripPrefix=1
                - name: DynamicHeader
                  args:
                    headers[0].name: X-User-Id
                    headers[0].value: spel:#claims['sub']

            - id: authorization-rest-api
              uri: http://localhost:8080
              predicates:
                - Path=/api/public/authorize/**
              filters:
                - StripPrefix=2