logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8090
spring:
  config:
    import: classpath:application-secrets.yml
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: employee-rest-api
              uri: http://localhost:8081
              predicates:
                - Path=/api/employee/**
              filters:
                - StripPrefix=1

            - id: authorization-rest-api
              uri: http://localhost:8080
              predicates:
                - Path=/api/public/authorize/**
              filters:
                - StripPrefix=2