logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  profiles:
    default: local
  config:
    import: classpath:application-secrets.yml
  application:
    name: business
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode=none
    show-sql: true
    open-in-view: false
encrypt:
  iv:
    length: 12
    t-len: 128
hashing:
  mac:
    algorithm: HmacSHA256
