server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/jobbydata
    username: root
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: admin
      database: jobby
