spring:
  profiles:
    default: local
  config:
    import: classpath:application-secrets.yml
  application:
    name: employee
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
